### ISSUE TITLE
fw-data update always fails with Xe driver and Arc A750

### ISSUE THREAD

**Issue by nokia8801** [intel/igsc#13]
- **OS:** Arch Linux
- **Kernel:** Linux 6.12.1-arch1-1
- **igsc:** 0.9.5
- **GPU:** Intel Arc A750 Limited Edition
- Using the Xe kernel driver

```
$ sudo igsc list-devices
Device [1] '/dev/mei1': 8086:56a1 8086:1021 0000:03:00.00
```

`fw update`, `oprom-data update` and `oprom-code update` all work without issues, except `fw-data update`. It never works for me. I'm getting the firmware files from [TechPowerUp](https://www.techpowerup.com/forums/threads/intel-arc-firmware-compilation-matrix.312440/), you can see the latest version 101.6314 released on December 4th, if you click on Spoiler: Firmware Matrix. 

- `dg2_gfx_fwupdate_SOC1.bin` for `fw update` from "SOC1 (A770/A750/A580)(M) Firmware" column, file "DG02_1.3266"
- `dg2_d_intel_a750_oprom-data.rom` for `oprom-data update` from "OPROM (DG2)" column, file "Intel A750:
[14 00 2C 04 00 00 00 00]"
- `dg2_c_oprom.rom` for `oprom-code update` from "OPROM (DG2)" column, file "DG2:
[14 00 31 04 00 00 00 00]"
- `fwdata/dg2_intel_a750_config-data.bin` for `fw-data update` from "OPROM (DG2)" column, file "FW Data", unzip it

`fw-data update` does not work. The others work without issues. Error:
```
$ sudo igsc fw-data update -a --device /dev/mei1 --image fwdata/dg2_intel_a750_config-data.bin
Image:  Fw Data Version: Format 1, Major Version: 101, OEM Manufacturing Data Version: 15, Major VCN: 1
    OEM Manufacturing Data Version FITB: 999999, Flags: 0X00000000, ARB SVN: 999999, ARB SVN FITB: 999999
Device: Fw Data Version: Format 1, Major Version: 101, OEM Manufacturing Data Version: 15, Major VCN: 1
    OEM Manufacturing Data Version FITB: 999999, Flags: 0X00000000, ARB SVN: 999999, ARB SVN FITB: 999999
Error: firmware data version is not compatible with the installed one (OEM version)
```

I was also wondering how can we use the files in "(DP/HDMI) PCON FW (DG2)" column? My monitor isn't detected most of the time after fresh boot, I have to unplug and replug both the PC and monitor every single time. I assume the DP firmware update would fix it? `dg2_pcon_fw.bin` how do I flash this with igsc? And where?

Edit: It also fails with i915 kernel driver.

**Comment by ausyskin** [comment]
"Error: firmware data version is not compatible with the installed one" - look like you trying to update to the same version as one that device already have - this is disallowed.

**Comment by ausyskin** [comment]
"OEM Manufacturing Data Version: 15" - looks the same.
And you have above error with -a too?

**Comment by nokia8801** [comment]
Yes, in fact, I just checked TechPowerUp again and saw that there is a new driver version 101.6325 from Dec 13th, 2024
WHQL which is not beta. So I just tried installing the necessary files from there again.

These worked with no issues:
```
$ sudo igsc fw update -a --device /dev/mei1 --image dg2_gfx_fwupdate_SOC1.bin
$ sudo igsc oprom-data update -a --device /dev/mei1 --image dg2_d_intel_a750_oprom-data.rom
$ sudo igsc oprom-code update -a --device /dev/mei1 --image dg2_c_oprom.rom
```

Except fw-data update:
```
$ sudo igsc fw-data update -a --device /dev/mei1 --image fwdata/dg2_intel_a750_config-data.bin

Image:  Fw Data Version: Format 1, Major Version: 101, OEM Manufacturing Data Version: 15, Major VCN: 1
    OEM Manufacturing Data Version FITB: 999999, Flags: 0X00000000, ARB SVN: 999999, ARB SVN FITB: 999999
Device: Fw Data Version: Format 1, Major Version: 101, OEM Manufacturing Data Version: 15, Major VCN: 1
    OEM Manufacturing Data Version FITB: 999999, Flags: 0X00000000, ARB SVN: 999999, ARB SVN FITB: 999999
Error: firmware data version is not compatible with the installed one (OEM version)
```

**Comment by ausyskin** [comment]
The upgrade on same OEM version is disabled and can't be overridden by flags.
Anyway - the blob is the same as you have on device. There is no point in update.

**Comment by ausyskin** [comment]
yes.

About DP/HDMI - not in the list of images updated by IGSC, can't help here.

**Comment by nokia8801** [comment]
Ok since the fw-data  update issue will pass once the file changes, I guess I'll close this issue.

Are there plans to add PCON firmware updating capability to igsc? Is it even possible? Thanks.

**Comment by ausyskin** [comment]
> Are there plans to add PCON firmware updating capability to igsc? Is it even possible? Thanks.
Do not think so, PCON is not the part of the interface that igsc uses.
